### PR TITLE
Update to test with Travis (#49)

### PR DESCRIPTION
**Pull request by sunshinekitty**
Also sneaking in
- Dockerfile stages, Go update to 1.9
- web version locking with yarn

### CODE REVIEW

**Comment by trevrosen** [comment]
@sunshinekitty thanks this is great. Quick question: does this mean that we're running Travis on *pushes* of topic branches? I think that's thrash tbh. I'd like to run on all PRs, but not on other pushes.

**Comment by sunshinekitty** [comment]
@trevrosen yea, we can change to just do pr's.  I thought it'd be useful to test branches for master updates.  If we move to a workflow of pr's from forks we shouldn't get a lot of extra testing on topic branches.

**Comment by trevrosen** [comment]
@sunshinekitty yeah PRs should be from forks unless they're internal to Bypass. I'm not sure what you mean about `test branches for master updates` -- can you elaborate?

**Comment by sunshinekitty** [comment]
@trevrosen after we merge a branch into master I think we should test the merge commit (this will then reflect on the status badge)

**Comment by trevrosen** [comment]
Ok sure fair enough.

**Comment by trevrosen** [comment]
@sunshinekitty if this does Yarn stuff, where does that leave #47? are you going to close that out? I think the non-standard k8s client is a deal breaker unfortunately.

**Comment by trevrosen** [comment]
Also please close the issue when you merge. 😸

**Comment by sunshinekitty** [comment]
@trevrosen yea planning to close out #47

**Comment by trevrosen** [comment]
@sunshinekitty cool deal. in my last I was actually referring to #49 as well, since it doesn't look like you added the magic `Fixes #49` to your commits for auto close.

**Pull request merged**
